---
apiVersion: v1
kind: Service
metadata:
  name: k8s-bom
  labels:
    app: k8s-bom
spec:
  ports:
    - port: 5000
  selector:
    app: k8s-bom
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bom
  labels:
    app: k8s-bom
spec:
  selector:
    matchLabels:
      app: k8s-bom
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: k8s-bom
    spec:
      containers:
      - image: jokercat2886/test-jenkins:latest
        name: k8s-bom
        env:
        ports:
        - containerPort: 5000
          name: k8s-bom
